# Generated by Django 5.1.6 on 2025-02-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="artist",
            fields=[
                ("artis_no", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("desc", models.TextField()),
            ],
        ),
    ]
