# Generated by Django 5.1.6 on 2025-02-20 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="artist",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
