# Generated by Django 5.1.6 on 2025-02-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="genre",
            fields=[
                ("genre_no", models.AutoField(primary_key=True, serialize=False)),
                ("genre", models.CharField(max_length=100, unique=True)),
                ("desc", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
    
